/*DROP TABLE LESSON_PARTICIPANTS;
DROP TABLE LESSON;
DROP TABLE TEACHER;
DROP TABLE DEGREE;
DROP TABLE CLASS_ROOM;*/

CREATE TABLE class_room (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	building VARCHAR(30),
	room_nb INT,
	capacity INT
);

CREATE TABLE degree(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name VARCHAR(30) UNIQUE,
	student_counts INT
);


CREATE TABLE user (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
	email VARCHAR(30) UNIQUE, 
	first_name VARCHAR(30),
	last_name VARCHAR(30), 
	password VARCHAR(64),
	is_admin BOOLEAN
);


CREATE TABLE lesson (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
	time_start TIMESTAMP,
	time_end TIMESTAMP, 
	title VARCHAR(30), 
	class_room_id INT REFERENCES class_room,
	teacher_id INT REFERENCES user 
);


CREATE TABLE lesson_participants(
	degree_id INT REFERENCES degree,
	lesson_id INT REFERENCES lesson
);

